export const produse = [
  {
    _id: '621235e59540445b3sdfe9s0',
    nume: 'Samsung Galaxy Z Flip4 5G',
    image: '/images/flip.jpg',
    descriere:
      "Introducing Samsung Galaxy Z Flip4. Fold it, flip it, stand it. Capture photos and videos hands-free with a camera designed to stand on its own with revolutionary folding glass or get that quick selfie when folded for moments that can't wait. ",
    brand: 'Samsung',
    categorie: 'Phone',
    pret: 599.99,
    rating: 3,
    numReviews: 1,
    isNew: true,
    reviews: [],
    stoc: 7,
  },
  {
    _id: '636985e59540445b3c45e6af',
    nume: 'iPhone 13 Pro 256GB Memory',
    image: '/images/iphone.jpg',
    descriere:
      'Shoot 4K video, beautiful portraits and sweeping landscapes with the all-new dual-camera system. Capture your best low-light photos with Night mode. See true-to-life colour in your photos, videos and games on the 6.1-inch Liquid Retina display.3 Experience unprecedented performance with A13 Bionic for gaming, augmented reality and photography',
    brand: 'Apple',
    categorie: 'Phone',
    pret: 929.99,
    rating: 3,
    numReviews: 1,
    isNew: false,

    reviews: [],
    stoc: 5,
  },
  {
    _id: '6369860d9540445b3c45e6b1',
    nume: 'Apple Watch SE 40mm',
    image: '/images/apple-watch.jpg',
    descriere:
      "Galaxy Tab S6 Lite is your super carriable note-taking, go-getting companion. It comes with a large 10.4 inch display on a slim and light build, One UI 4 on Android, and S Pen in box and ready to go. Whether you're drawing, learning or gaming, this is the tablet made to be in the moment. ",
    brand: 'Apple',
    categorie: 'Accesorie',
    pret: 399.99,
    countInStock: 11,
    rating: 4,
    numReviews: 10,
    isNew: false,

    reviews: [],
    stoc: 0,
  },
  {
    _id: '6369863c9540445b3c45e6b3',
    nume: 'Samsung Galaxy S20 Ultra',
    image: '/images/s22.jpg',
    descriere:
      'Meet the Galaxy Watch5. It comes with an innovative 3-in-1 BioActive Sensor designed to accurately monitor and help improve your health, a durable Aluminium finish and a stylish design built for the grind with 60% stronger Sapphire Crystal Glass.',
    brand: 'Samsung',
    categorie: 'Phone',
    pret: 299.99,
    rating: 5,
    numReviews: 2,
    isNew: false,

    reviews: [],
    stoc: 7,
  },
  {
    _id: '636986749540445b3c45e6b7',
    nume: 'HP Pavilion 15',
    image: '/images/pavilion 15.jpg',
    descriere:
      'Miss nothing, with Galaxy S21 5G. A camera so good, everyone’s a pro. When capturing your best moments, you no longer have to choose between photo and video. Galaxy S21 captures both, simultaneously, so you’ll never miss a moment. Capture big screen quality videos in stunning 8K resolution* and zoom in with less pixilation with 3x Optical Zoom.',
    brand: 'HP',
    categorie: 'Laptop',
    pret: 699.99,
    rating: 5,
    numReviews: 0,
    isNew: false,
    stoc: 0,
  },
  {
    _id: '63804a5079636c2ced47757d',
    nume: 'Mac Book Pro',
    image: '/images/mac-book-pro.jpg',
    brand: 'Apple',
    categorie: 'Laptop',
    descriere:
      'Essential features to help you stay connected, active, healthy and safe. Perfect for kids and older adults using Family Setup',
    rating: 0,
    numReviews: 0,
    pret: 699.99,
    stoc: 5,
    isNew: true,
    reviews: [],
  },
  {
    _id: '6381275e8e8648e00b7c82f7',
    nume: 'HP Omen',
    image: '/images/HP-Omen.jpg',
    brand: 'HP',
    categorie: 'Laptop',
    descriere:
      'Get a professional podcast sound with audio interfaces, hard disk recorders, or direct to computers and mobile devices with the Shure MV7 Podcasting Microphone (Black). This is a professional-quality, broadcast-style dynamic microphone, one that can has both a conventional XLR connection and a USB port. It also supports a 3.5mm headphone output for direct monitoring.',
    rating: 0,
    numReviews: 0,
    pret: 449,
    stoc: 2,
    isNew: true,
    reviews: [],
  },
  {
    _id: '63895d3b2a3e062504353022',
    nume: 'Samsung Tab 5',
    image: '/images/tab.jpg',
    brand: 'Samsung',
    categorie: 'Tablet',
    descriere:
      "Blazing 5G. Powerfully connected. It's time to enter into the next chapter. Seriously-fast 5G connection takes your everyday mobile experiences and vastly enhances them with next-level speed. Feel truly connected with seamless streaming, instant sharing and the power to transfer your thoughts to action in a blink.",
    rating: 5,
    numReviews: 1,
    pret: 899.99,
    stoc: 49,
    isNew: true,
    reviews: [],
  },
];
